/*
 * This file is generated by jOOQ.
 */
package persistence.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import persistence.tables.UserPreferencesEntity;
import persistence.tables.records.UserPreferencesEntityRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPreferencesEntityDao extends DAOImpl<UserPreferencesEntityRecord, persistence.tables.pojos.UserPreferencesEntity, Integer> {

    /**
     * Create a new UserPreferencesEntityDao without any configuration
     */
    public UserPreferencesEntityDao() {
        super(UserPreferencesEntity.USER_PREFERENCES_ENTITY, persistence.tables.pojos.UserPreferencesEntity.class);
    }

    /**
     * Create a new UserPreferencesEntityDao with an attached configuration
     */
    public UserPreferencesEntityDao(Configuration configuration) {
        super(UserPreferencesEntity.USER_PREFERENCES_ENTITY, persistence.tables.pojos.UserPreferencesEntity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(persistence.tables.pojos.UserPreferencesEntity object) {
        return object.getUserfk();
    }

    /**
     * Fetch records that have <code>userfk IN (values)</code>
     */
    public List<persistence.tables.pojos.UserPreferencesEntity> fetchByUserfk(Integer... values) {
        return fetch(UserPreferencesEntity.USER_PREFERENCES_ENTITY.USERFK, values);
    }

    /**
     * Fetch a unique record that has <code>userfk = value</code>
     */
    public persistence.tables.pojos.UserPreferencesEntity fetchOneByUserfk(Integer value) {
        return fetchOne(UserPreferencesEntity.USER_PREFERENCES_ENTITY.USERFK, value);
    }

    /**
     * Fetch records that have <code>sourceLanguagefk IN (values)</code>
     */
    public List<persistence.tables.pojos.UserPreferencesEntity> fetchBySourcelanguagefk(Integer... values) {
        return fetch(UserPreferencesEntity.USER_PREFERENCES_ENTITY.SOURCELANGUAGEFK, values);
    }

    /**
     * Fetch records that have <code>targetLanguagefk IN (values)</code>
     */
    public List<persistence.tables.pojos.UserPreferencesEntity> fetchByTargetlanguagefk(Integer... values) {
        return fetch(UserPreferencesEntity.USER_PREFERENCES_ENTITY.TARGETLANGUAGEFK, values);
    }
}
