/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageEntity implements Serializable {

    private static final long serialVersionUID = -1083157171;

    private Integer id;
    private String  slug;
    private String  name;
    private Integer isgateway;
    private String  anglicizedname;

    public LanguageEntity() {}

    public LanguageEntity(LanguageEntity value) {
        this.id = value.id;
        this.slug = value.slug;
        this.name = value.name;
        this.isgateway = value.isgateway;
        this.anglicizedname = value.anglicizedname;
    }

    public LanguageEntity(
        Integer id,
        String  slug,
        String  name,
        Integer isgateway,
        String  anglicizedname
    ) {
        this.id = id;
        this.slug = slug;
        this.name = name;
        this.isgateway = isgateway;
        this.anglicizedname = anglicizedname;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIsgateway() {
        return this.isgateway;
    }

    public void setIsgateway(Integer isgateway) {
        this.isgateway = isgateway;
    }

    public String getAnglicizedname() {
        return this.anglicizedname;
    }

    public void setAnglicizedname(String anglicizedname) {
        this.anglicizedname = anglicizedname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LanguageEntity (");

        sb.append(id);
        sb.append(", ").append(slug);
        sb.append(", ").append(name);
        sb.append(", ").append(isgateway);
        sb.append(", ").append(anglicizedname);

        sb.append(")");
        return sb.toString();
    }
}
