/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLanguagesEntity implements Serializable {

    private static final long serialVersionUID = 232284767;

    private Integer userfk;
    private Integer languagefk;
    private Integer issource;

    public UserLanguagesEntity() {}

    public UserLanguagesEntity(UserLanguagesEntity value) {
        this.userfk = value.userfk;
        this.languagefk = value.languagefk;
        this.issource = value.issource;
    }

    public UserLanguagesEntity(
        Integer userfk,
        Integer languagefk,
        Integer issource
    ) {
        this.userfk = userfk;
        this.languagefk = languagefk;
        this.issource = issource;
    }

    public Integer getUserfk() {
        return this.userfk;
    }

    public void setUserfk(Integer userfk) {
        this.userfk = userfk;
    }

    public Integer getLanguagefk() {
        return this.languagefk;
    }

    public void setLanguagefk(Integer languagefk) {
        this.languagefk = languagefk;
    }

    public Integer getIssource() {
        return this.issource;
    }

    public void setIssource(Integer issource) {
        this.issource = issource;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserLanguagesEntity (");

        sb.append(userfk);
        sb.append(", ").append(languagefk);
        sb.append(", ").append(issource);

        sb.append(")");
        return sb.toString();
    }
}
