/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntity implements Serializable {

    private static final long serialVersionUID = -1705267875;

    private Integer id;
    private String  audiohash;
    private String  audiopath;
    private String  imgpath;

    public UserEntity() {}

    public UserEntity(UserEntity value) {
        this.id = value.id;
        this.audiohash = value.audiohash;
        this.audiopath = value.audiopath;
        this.imgpath = value.imgpath;
    }

    public UserEntity(
        Integer id,
        String  audiohash,
        String  audiopath,
        String  imgpath
    ) {
        this.id = id;
        this.audiohash = audiohash;
        this.audiopath = audiopath;
        this.imgpath = imgpath;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAudiohash() {
        return this.audiohash;
    }

    public void setAudiohash(String audiohash) {
        this.audiohash = audiohash;
    }

    public String getAudiopath() {
        return this.audiopath;
    }

    public void setAudiopath(String audiopath) {
        this.audiopath = audiopath;
    }

    public String getImgpath() {
        return this.imgpath;
    }

    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserEntity (");

        sb.append(id);
        sb.append(", ").append(audiohash);
        sb.append(", ").append(audiopath);
        sb.append(", ").append(imgpath);

        sb.append(")");
        return sb.toString();
    }
}
