/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPreferencesEntity implements Serializable {

    private static final long serialVersionUID = -1325527255;

    private Integer userfk;
    private Integer sourcelanguagefk;
    private Integer targetlanguagefk;

    public UserPreferencesEntity() {}

    public UserPreferencesEntity(UserPreferencesEntity value) {
        this.userfk = value.userfk;
        this.sourcelanguagefk = value.sourcelanguagefk;
        this.targetlanguagefk = value.targetlanguagefk;
    }

    public UserPreferencesEntity(
        Integer userfk,
        Integer sourcelanguagefk,
        Integer targetlanguagefk
    ) {
        this.userfk = userfk;
        this.sourcelanguagefk = sourcelanguagefk;
        this.targetlanguagefk = targetlanguagefk;
    }

    public Integer getUserfk() {
        return this.userfk;
    }

    public void setUserfk(Integer userfk) {
        this.userfk = userfk;
    }

    public Integer getSourcelanguagefk() {
        return this.sourcelanguagefk;
    }

    public void setSourcelanguagefk(Integer sourcelanguagefk) {
        this.sourcelanguagefk = sourcelanguagefk;
    }

    public Integer getTargetlanguagefk() {
        return this.targetlanguagefk;
    }

    public void setTargetlanguagefk(Integer targetlanguagefk) {
        this.targetlanguagefk = targetlanguagefk;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPreferencesEntity (");

        sb.append(userfk);
        sb.append(", ").append(sourcelanguagefk);
        sb.append(", ").append(targetlanguagefk);

        sb.append(")");
        return sb.toString();
    }
}
