/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.UserEntity;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntityRecord extends UpdatableRecordImpl<UserEntityRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 10193660;

    /**
     * Setter for <code>USER ENTITY.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USER ENTITY.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USER ENTITY.audioHash</code>.
     */
    public void setAudiohash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>USER ENTITY.audioHash</code>.
     */
    public String getAudiohash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>USER ENTITY.audioPath</code>.
     */
    public void setAudiopath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>USER ENTITY.audioPath</code>.
     */
    public String getAudiopath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>USER ENTITY.imgPath</code>.
     */
    public void setImgpath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>USER ENTITY.imgPath</code>.
     */
    public String getImgpath() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserEntity.USER_ENTITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserEntity.USER_ENTITY.AUDIOHASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserEntity.USER_ENTITY.AUDIOPATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserEntity.USER_ENTITY.IMGPATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAudiohash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAudiopath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getImgpath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAudiohash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAudiopath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getImgpath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value2(String value) {
        setAudiohash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value3(String value) {
        setAudiopath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value4(String value) {
        setImgpath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserEntityRecord
     */
    public UserEntityRecord() {
        super(UserEntity.USER_ENTITY);
    }

    /**
     * Create a detached, initialised UserEntityRecord
     */
    public UserEntityRecord(Integer id, String audiohash, String audiopath, String imgpath) {
        super(UserEntity.USER_ENTITY);

        set(0, id);
        set(1, audiohash);
        set(2, audiopath);
        set(3, imgpath);
    }
}
