/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import javax.annotation.Generated;

import jooq.tables.UserLanguagesEntity;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLanguagesEntityRecord extends UpdatableRecordImpl<UserLanguagesEntityRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1016099045;

    /**
     * Setter for <code>USER LANGUAGES ENTITY.userfk</code>.
     */
    public void setUserfk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USER LANGUAGES ENTITY.userfk</code>.
     */
    public Integer getUserfk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USER LANGUAGES ENTITY.languagefk</code>.
     */
    public void setLanguagefk(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>USER LANGUAGES ENTITY.languagefk</code>.
     */
    public Integer getLanguagefk() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>USER LANGUAGES ENTITY.isSource</code>.
     */
    public void setIssource(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>USER LANGUAGES ENTITY.isSource</code>.
     */
    public Integer getIssource() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserLanguagesEntity.USER_LANGUAGES_ENTITY.USERFK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserLanguagesEntity.USER_LANGUAGES_ENTITY.LANGUAGEFK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserLanguagesEntity.USER_LANGUAGES_ENTITY.ISSOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserfk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLanguagefk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getIssource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserfk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLanguagefk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIssource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguagesEntityRecord value1(Integer value) {
        setUserfk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguagesEntityRecord value2(Integer value) {
        setLanguagefk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguagesEntityRecord value3(Integer value) {
        setIssource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLanguagesEntityRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserLanguagesEntityRecord
     */
    public UserLanguagesEntityRecord() {
        super(UserLanguagesEntity.USER_LANGUAGES_ENTITY);
    }

    /**
     * Create a detached, initialised UserLanguagesEntityRecord
     */
    public UserLanguagesEntityRecord(Integer userfk, Integer languagefk, Integer issource) {
        super(UserLanguagesEntity.USER_LANGUAGES_ENTITY);

        set(0, userfk);
        set(1, languagefk);
        set(2, issource);
    }
}
