/*
 * This file is generated by jOOQ.
 */
package persistence.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import persistence.tables.LanguageEntity;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageEntityRecord extends UpdatableRecordImpl<LanguageEntityRecord> implements Record5<Integer, String, String, Integer, String> {

    private static final long serialVersionUID = -1352473715;

    /**
     * Setter for <code>LANGUAGE ENTITY.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LANGUAGE ENTITY.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LANGUAGE ENTITY.slug</code>.
     */
    public void setSlug(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LANGUAGE ENTITY.slug</code>.
     */
    public String getSlug() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LANGUAGE ENTITY.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>LANGUAGE ENTITY.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>LANGUAGE ENTITY.isGateway</code>.
     */
    public void setIsgateway(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>LANGUAGE ENTITY.isGateway</code>.
     */
    public Integer getIsgateway() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>LANGUAGE ENTITY.anglicizedName</code>.
     */
    public void setAnglicizedname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>LANGUAGE ENTITY.anglicizedName</code>.
     */
    public String getAnglicizedname() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return LanguageEntity.LANGUAGE_ENTITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return LanguageEntity.LANGUAGE_ENTITY.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return LanguageEntity.LANGUAGE_ENTITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return LanguageEntity.LANGUAGE_ENTITY.ISGATEWAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return LanguageEntity.LANGUAGE_ENTITY.ANGLICIZEDNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getIsgateway();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAnglicizedname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIsgateway();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAnglicizedname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LanguageEntityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LanguageEntityRecord value2(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LanguageEntityRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LanguageEntityRecord value4(Integer value) {
        setIsgateway(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LanguageEntityRecord value5(String value) {
        setAnglicizedname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LanguageEntityRecord values(Integer value1, String value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LanguageEntityRecord
     */
    public LanguageEntityRecord() {
        super(LanguageEntity.LANGUAGE_ENTITY);
    }

    /**
     * Create a detached, initialised LanguageEntityRecord
     */
    public LanguageEntityRecord(Integer id, String slug, String name, Integer isgateway, String anglicizedname) {
        super(LanguageEntity.LANGUAGE_ENTITY);

        set(0, id);
        set(1, slug);
        set(2, name);
        set(3, isgateway);
        set(4, anglicizedname);
    }
}
