/*
 * This file is generated by jOOQ.
 */
package persistence.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import persistence.tables.UserPreferencesEntity;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPreferencesEntityRecord extends UpdatableRecordImpl<UserPreferencesEntityRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1549135317;

    /**
     * Setter for <code>USER PREFERENCES ENTITY.userfk</code>.
     */
    public void setUserfk(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USER PREFERENCES ENTITY.userfk</code>.
     */
    public Integer getUserfk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USER PREFERENCES ENTITY.sourceLanguagefk</code>.
     */
    public void setSourcelanguagefk(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>USER PREFERENCES ENTITY.sourceLanguagefk</code>.
     */
    public Integer getSourcelanguagefk() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>USER PREFERENCES ENTITY.targetLanguagefk</code>.
     */
    public void setTargetlanguagefk(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>USER PREFERENCES ENTITY.targetLanguagefk</code>.
     */
    public Integer getTargetlanguagefk() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserPreferencesEntity.USER_PREFERENCES_ENTITY.USERFK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserPreferencesEntity.USER_PREFERENCES_ENTITY.SOURCELANGUAGEFK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserPreferencesEntity.USER_PREFERENCES_ENTITY.TARGETLANGUAGEFK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserfk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSourcelanguagefk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTargetlanguagefk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserfk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSourcelanguagefk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTargetlanguagefk();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPreferencesEntityRecord value1(Integer value) {
        setUserfk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPreferencesEntityRecord value2(Integer value) {
        setSourcelanguagefk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPreferencesEntityRecord value3(Integer value) {
        setTargetlanguagefk(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPreferencesEntityRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPreferencesEntityRecord
     */
    public UserPreferencesEntityRecord() {
        super(UserPreferencesEntity.USER_PREFERENCES_ENTITY);
    }

    /**
     * Create a detached, initialised UserPreferencesEntityRecord
     */
    public UserPreferencesEntityRecord(Integer userfk, Integer sourcelanguagefk, Integer targetlanguagefk) {
        super(UserPreferencesEntity.USER_PREFERENCES_ENTITY);

        set(0, userfk);
        set(1, sourcelanguagefk);
        set(2, targetlanguagefk);
    }
}
