/*
 * This file is generated by jOOQ.
 */
package persistence.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import persistence.DefaultSchema;
import persistence.Keys;
import persistence.tables.records.UserPreferencesEntityRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPreferencesEntity extends TableImpl<UserPreferencesEntityRecord> {

    private static final long serialVersionUID = 1863973283;

    /**
     * The reference instance of <code>USER PREFERENCES ENTITY</code>
     */
    public static final UserPreferencesEntity USER_PREFERENCES_ENTITY = new UserPreferencesEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserPreferencesEntityRecord> getRecordType() {
        return UserPreferencesEntityRecord.class;
    }

    /**
     * The column <code>USER PREFERENCES ENTITY.userfk</code>.
     */
    public final TableField<UserPreferencesEntityRecord, Integer> USERFK = createField("userfk", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USER PREFERENCES ENTITY.sourceLanguagefk</code>.
     */
    public final TableField<UserPreferencesEntityRecord, Integer> SOURCELANGUAGEFK = createField("sourceLanguagefk", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USER PREFERENCES ENTITY.targetLanguagefk</code>.
     */
    public final TableField<UserPreferencesEntityRecord, Integer> TARGETLANGUAGEFK = createField("targetLanguagefk", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>USER PREFERENCES ENTITY</code> table reference
     */
    public UserPreferencesEntity() {
        this(DSL.name("USER PREFERENCES ENTITY"), null);
    }

    /**
     * Create an aliased <code>USER PREFERENCES ENTITY</code> table reference
     */
    public UserPreferencesEntity(String alias) {
        this(DSL.name(alias), USER_PREFERENCES_ENTITY);
    }

    /**
     * Create an aliased <code>USER PREFERENCES ENTITY</code> table reference
     */
    public UserPreferencesEntity(Name alias) {
        this(alias, USER_PREFERENCES_ENTITY);
    }

    private UserPreferencesEntity(Name alias, Table<UserPreferencesEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserPreferencesEntity(Name alias, Table<UserPreferencesEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserPreferencesEntity(Table<O> child, ForeignKey<O, UserPreferencesEntityRecord> key) {
        super(child, key, USER_PREFERENCES_ENTITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserPreferencesEntityRecord> getPrimaryKey() {
        return Keys.PK_USER_PREFERENCES_ENTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserPreferencesEntityRecord>> getKeys() {
        return Arrays.<UniqueKey<UserPreferencesEntityRecord>>asList(Keys.PK_USER_PREFERENCES_ENTITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPreferencesEntity as(String alias) {
        return new UserPreferencesEntity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPreferencesEntity as(Name alias) {
        return new UserPreferencesEntity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPreferencesEntity rename(String name) {
        return new UserPreferencesEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPreferencesEntity rename(Name name) {
        return new UserPreferencesEntity(name, null);
    }
}
