/*
 * This file is generated by jOOQ.
 */
package persistence;


import javax.annotation.Generated;

import persistence.tables.LanguageEntity;
import persistence.tables.SqliteSequence;
import persistence.tables.UserEntity;
import persistence.tables.UserLanguagesEntity;
import persistence.tables.UserPreferencesEntity;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>LANGUAGE ENTITY</code>.
     */
    public static final LanguageEntity LANGUAGE_ENTITY = persistence.tables.LanguageEntity.LANGUAGE_ENTITY;

    /**
     * The table <code>USER ENTITY</code>.
     */
    public static final UserEntity USER_ENTITY = persistence.tables.UserEntity.USER_ENTITY;

    /**
     * The table <code>USER LANGUAGES ENTITY</code>.
     */
    public static final UserLanguagesEntity USER_LANGUAGES_ENTITY = persistence.tables.UserLanguagesEntity.USER_LANGUAGES_ENTITY;

    /**
     * The table <code>USER PREFERENCES ENTITY</code>.
     */
    public static final UserPreferencesEntity USER_PREFERENCES_ENTITY = persistence.tables.UserPreferencesEntity.USER_PREFERENCES_ENTITY;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = persistence.tables.SqliteSequence.SQLITE_SEQUENCE;
}
